name: GitHub Actions のお試し

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: Homebrew/actions/setup-homebrew@master
              with:
                core: true
                cask: true
                test-bot: false
            - run: which brew